version: '3.8'
services:

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=thechef
      - POSTGRES_PASSWORD=letscook
      - POSTGRES_DB=recipes_db
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  data:
