# Generated by Django 4.0.2 on 2022-02-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название ингредиента')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.DeleteModel(
            name='Ingridient',
        ),
        migrations.AlterField(
            model_name='meal',
            name='ingridients',
            field=models.ManyToManyField(related_name='meals', to='recipebook.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
