# Generated by Django 4.0.2 on 2022-02-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0002_ingredient_delete_ingridient_alter_meal_ingridients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='ingridients',
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(related_name='meals', to='recipebook.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
